version: "3.8"
services:
  firstNode:
    image: denzhid/simpleblockchain
    container_name: firstNode
    network_mode: host
    command: java -jar /simpleblockchain/build/libs/SimpleBlockChain-1.0.jar
    environment:
      CURRENT_NODE_ADDRESS: 127.0.0.1:3000
      NODES_IN_CLUSTER_ADDRESSES: 127.0.0.1:3001,127.0.0.1:3002
      IS_GENESIS: FALSE

  secondNode:
    image: denzhid/simpleblockchain
    container_name: secondNode
    network_mode: host
    command: java -jar /simpleblockchain/build/libs/SimpleBlockChain-1.0.jar
    environment:
      CURRENT_NODE_ADDRESS: 127.0.0.1:3001
      NODES_IN_CLUSTER_ADDRESSES: 127.0.0.1:3000,127.0.0.1:3002
      IS_GENESIS: FALSE

  thirdNode:
    depends_on:
      - firstNode
      - secondNode
    image: denzhid/simpleblockchain
    container_name: thirdNode
    network_mode: host
    command: java -jar /simpleblockchain/build/libs/SimpleBlockChain-1.0.jar
    environment:
      CURRENT_NODE_ADDRESS: 127.0.0.1:3002
      NODES_IN_CLUSTER_ADDRESSES: 127.0.0.1:3000,127.0.0.1:3001
      IS_GENESIS: TRUE